services:
  - type: web
    name: plant-disease-predictor
    env: docker
    plan: free # Change depending on requirements (TensorFlow might require a paid tier due to memory)
    region: oregon
    envVars:
      - key: PORT
        value: 5000
    dockerCommand: gunicorn -b 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app
